### ISSUE TITLE
Typo in base-wind.csproj file

### ISSUE THREAD

**Issue by klr324** [LANDIS-II-Foundation/Extension-Base-Wind#10]
Typo in base-wind.csproj file where the .dll has the wrong name:

<Reference Include="Landis.Library.Cohorts-v2">
      <HintPath>lib\Landis.Library.ALandis.Library.Cohorts-v2.dll</HintPath>
</Reference>

It should be:
<Reference Include="Landis.Library.Cohorts-v2">
      <HintPath>lib\Landis.Library.Cohorts-v2.dll</HintPath>
</Reference>

**Comment by rmscheller** [comment]
Corrected. Thanks again!
