### ISSUE TITLE
Summary log and events log do not respect the path and names given in the parameter file

### ISSUE THREAD

**Issue by Klemet** [LANDIS-II-Foundation/Extension-Base-Wind#14]
Everything is in the title !

Whatever the path given in the Base Wind parameter file, it always save in the root of the simulation in `wind-events-log.csv` and `wind-summary-log.csv`.

See the test files supplied in #13 for evidence, as the behaviour can be seen there.

**Comment by rmscheller** [comment]
Clement,
There are a couple of options here.  
1) respect the input file name given,
2) force all output files into a 'wind' sub-directory.

I favor the second because, a) most users do not care about the output file name, b) it will be much easier to code it so that all wind outputs, maps and tables, are written to the same sub-directory.  

What are your thoughts?  Thanks!

Rob

**Comment by Klemet** [comment]
Hello, Rob !

A `wind` sub-directory would be best among the two I believe, yes; but I thought that using the code in another extension with a system of outputs that respects the path given (like Base Fire) might do the trick ?

**Comment by rmscheller** [comment]
Clement,

I followed your advise and added the user determined path/name for summary and event log files.  Could you try v3.2 and see if it resolves your issue?  Note that you will need to change the input to SummaryLogFileName and add EventLogFileName.  This is a quick fix to see if it fixes the problem.  A new version won't be released until Core v8 is released.

**Comment by Klemet** [comment]
Thank you Rob 😄 ! I hope this didn't take too much of your time; I didn't think this was too much of an urgent issue, but I thought to point it out noneless.

Right now, trying v3.2 : 
- `EventLogFile` is required rather than `EventLogFileName` as you pointed out in your message
- I get the following error when running a test simulation : `Could not find a part of the path 'D:\testWind3.2\output\wind\WindEventlog.csv'.`. This happens during the initialization. I've tried different folders, but no changes. Here are the test files : 

[testWind3.2.zip](https://github.com/LANDIS-II-Foundation/Extension-Base-Wind/files/14775321/testWind3.2.zip)

**Comment by rmscheller** [comment]
Hm.  I have no idea why it doesn't like your path.  Maybe go back to option #1 whereby the file names are hardcoded?  The advantage to that is that they will be consistent across all users.

**Comment by Klemet** [comment]
After some testing, it seems like it's simply not able to create a folder; so every folder along the path must be created for it to work and initialize the Summary and Event logs. After that, everything works fine, just like for Base Fire !

I think I found out why. In Base fire, the `MetadataHandler.cs` file contains two lines of codes used to create the folder ([here](https://github.com/LANDIS-II-Foundation/Extension-Base-Fire/blob/14e84fde7bbcae7445e39b7e0128ab156aaeedaa/src/MetadataHandler.cs#L39)) : 

```C#
CreateDirectory(eventLogName);
CreateDirectory(summaryLogName);
```

With the `CreateDirectory` function being defined at the end of the file as : 

```C#
        public static void CreateDirectory(string path)
        {
            //Require.ArgumentNotNull(path);
            path = path.Trim(null);
            if (path.Length == 0)
                throw new ArgumentException("path is empty or just whitespace");
            //throw new Exception(path);
            string dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir))
            {
                Flel.Directory.EnsureExists(dir);
            }

            //return new StreamWriter(path);
            return;
        }
```

These two lines and the function do not exist in the current version of `MetadataHandler.cs` for Base Wind. If they are added at [line 34 of MetadataHandler.cs](https://github.com/LANDIS-II-Foundation/Extension-Base-Wind/blob/31da40d548d3e627c8162c207fce65f289d8bfdb/src/MetadataHandler.cs#L34) , and if `CreateDirectory` function is then added at the end of the code, then everything should work fine, I believe 😄 !

**Comment by rmscheller** [comment]
OK.  New installer committed.

**Comment by Klemet** [comment]
Everything seems to work fine ! Thank you 😄 !
